spring:
  profiles:
    active: rpc,sender,remote

  rabbitmq:
    host: 10.5.133.220
    username: guest
    password: guest
    
  datasource:
    url: jdbc:mysql://10.5.133.219:3306/test
    username: root
    password: dev@ats
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    database:
      MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
      
logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000
    
 
