spring:
  profiles:
    active: dev

  application:
    name: serv35-traincontrol

  zipkin:
    baseUrl: http://10.5.133.219:9411
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.5.133.219:8761/eureka/


info:
  app:
    artifact: "@project.artifact@"
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-artifact: "@project.parent.artifact@"
    spring-boot-version: "@project.parent.version@"

server:
 port: 60035